#!/usr/bin/env python3
"""BE. Defended-distribution prototype for set-point dynamics.

This is an exploratory model driven by the data structure, not by the EMA
or latch families.

Core idea:
  - The body does not carry a single defended fat mass.
  - It carries a memory distribution over historically occupied fat-mass
    levels.
  - Appetite pressure depends on where current FM sits relative to that
    defended distribution.
  - New defended memory consolidates continuously, but consolidation is
    slowed when FM is moving quickly.

This script does three things:
  1. Fits a small grid of defended-distribution models to this subject's
     2014+ pre-tirzepatide 90d mean surplus.
  2. Uses the same fitted model to simulate SURMOUNT-4-style post-drug regain
     with no separate discontinuation rule.
  3. Reports whether a single continuous law can plausibly bridge subject and
     trial behavior.
"""

from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
GRID_MIN = 10.0
GRID_MAX = 110.0
GRID_STEP = 0.5
FAT_FRACTION_REGAINED = 0.93
FAT_FRACTION_SUBJECT = 0.85


def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def gaussian_kernel(grid, center, sigma):
    k = np.exp(-0.5 * ((grid - center) / sigma) ** 2)
    s = k.sum()
    return k / s if s > 0 else np.zeros_like(grid)


def build_memory_pressure(fm, params, grid):
    """Generate a pressure raw score from a defended-distribution memory field."""
    sigma = params["kernel_sigma"]
    decay_hl = params["decay_hl_days"]
    cons_rate = params["cons_rate"]
    v_thresh = params["vel_thresh"]
    v_scale = params["vel_scale"]
    band = params["pressure_band"]

    decay = 1.0 - np.exp(-np.log(2) / decay_hl)
    memory = gaussian_kernel(grid, fm[0], sigma)
    raw = np.zeros(len(fm))
    gate = np.zeros(len(fm))

    for i in range(len(fm)):
        if i > 0:
            j = max(0, i - 14)
            vel = abs((fm[i] - fm[j]) / max(1, i - j))
            gate[i] = sigmoid((v_thresh - vel) / v_scale)
            memory = (1.0 - decay) * memory + cons_rate * gate[i] * gaussian_kernel(grid, fm[i], sigma)

        mass = memory.sum()
        if mass <= 0:
            raw[i] = 0.0
        else:
            mnorm = memory / mass
            # Positive raw means current FM sits below remembered higher-FM mass,
            # so the appetite/re-gain pressure should point upward.
            raw[i] = -np.sum(mnorm * np.tanh((grid - fm[i]) / band))

    return raw, gate


def fit_scale(raw, target):
    valid = ~np.isnan(raw) & ~np.isnan(target)
    if valid.sum() < 300:
        return np.nan, np.nan, 0
    x = raw[valid]
    y = target[valid]
    beta = np.linalg.lstsq(np.column_stack([x, np.ones(len(x))]), y, rcond=None)[0]
    pred = beta[0] * x + beta[1]
    r = np.corrcoef(pred, y)[0, 1]
    return beta[0], beta[1], r


def simulate_trial_regain(params, scale, intercept, start_fm, stop_fm, treatment_days, regain_days, week36_weight_lbs):
    """Treatment path is externally imposed; regain is generated by the same memory law."""
    grid = np.arange(GRID_MIN, GRID_MAX + GRID_STEP, GRID_STEP)
    sigma = params["kernel_sigma"]
    decay_hl = params["decay_hl_days"]
    cons_rate = params["cons_rate"]
    v_thresh = params["vel_thresh"]
    v_scale = params["vel_scale"]
    band = params["pressure_band"]

    decay = 1.0 - np.exp(-np.log(2) / decay_hl)
    memory = gaussian_kernel(grid, start_fm, sigma)

    fm_treat = np.linspace(start_fm, stop_fm, treatment_days)
    fm_path = list(fm_treat)

    for i in range(1, treatment_days):
        j = max(0, i - 14)
        vel = abs((fm_treat[i] - fm_treat[j]) / max(1, i - j))
        gate = sigmoid((v_thresh - vel) / v_scale)
        memory = (1.0 - decay) * memory + cons_rate * gate * gaussian_kernel(grid, fm_treat[i], sigma)

    fm_cur = stop_fm
    for _ in range(regain_days):
        mnorm = memory / memory.sum()
        raw = -np.sum(mnorm * np.tanh((grid - fm_cur) / band))
        surplus = scale * raw + intercept
        fm_cur += surplus * FAT_FRACTION_REGAINED / 3500.0
        fm_path.append(fm_cur)

        # Same consolidation law during regain.
        hist_idx = len(fm_path) - 1
        j = max(0, hist_idx - 14)
        vel = abs((fm_path[hist_idx] - fm_path[j]) / max(1, hist_idx - j))
        gate = sigmoid((v_thresh - vel) / v_scale)
        memory = (1.0 - decay) * memory + cons_rate * gate * gaussian_kernel(grid, fm_cur, sigma)

    regained_fm = fm_cur - stop_fm
    regained_weight = regained_fm / FAT_FRACTION_REGAINED
    regain_pct = regained_weight / week36_weight_lbs * 100.0
    return regain_pct


def load_subject():
    intake = pd.read_csv(ROOT / "intake" / "intake_daily.csv", parse_dates=["date"])
    kalman = pd.read_csv(ROOT / "analysis" / "P4_kalman_daily.csv", parse_dates=["date"])
    tirz = pd.read_csv(ROOT / "drugs" / "tirzepatide.csv", parse_dates=["date"])

    df = intake[["date", "calories"]].merge(
        kalman[["date", "fat_mass_lbs", "tdee"]], on="date", how="inner"
    )
    df = df.merge(tirz[["date", "effective_level"]], on="date", how="left")
    df["effective_level"] = df["effective_level"].fillna(0)
    df = df.sort_values("date").reset_index(drop=True)
    df["surplus"] = df["calories"] - df["tdee"]
    df["surplus_90"] = df["surplus"].rolling(90, min_periods=90).mean()

    fm = df["fat_mass_lbs"].values.copy()
    first_valid = np.where(~np.isnan(fm))[0][0]
    fm[:first_valid] = fm[first_valid]
    for i in range(first_valid + 1, len(fm)):
        if np.isnan(fm[i]):
            fm[i] = fm[i - 1]
    df["fat_mass_lbs_filled"] = fm
    return df


def main():
    df = load_subject()
    grid = np.arange(GRID_MIN, GRID_MAX + GRID_STEP, GRID_STEP)

    fit_mask = (df["date"] >= "2014-01-01") & (df["effective_level"] == 0)
    target = df["surplus_90"].values
    fm = df["fat_mass_lbs_filled"].values

    param_grid = []
    for decay_hl in [180, 365, 730, 1460]:
        for cons_rate in [0.01, 0.02, 0.04]:
            for v_thresh in [0.03, 0.05, 0.08]:
                for kernel_sigma in [1.5, 3.0]:
                    for pressure_band in [3.0, 6.0]:
                        param_grid.append({
                            "decay_hl_days": decay_hl,
                            "cons_rate": cons_rate,
                            "vel_thresh": v_thresh,
                            "vel_scale": 0.02,
                            "kernel_sigma": kernel_sigma,
                            "pressure_band": pressure_band,
                        })

    rows = []
    for params in param_grid:
        raw, gate = build_memory_pressure(fm, params, grid)
        scale, intercept, fit_r = fit_scale(raw[fit_mask.values], target[fit_mask.values])
        if np.isnan(scale):
            continue

        regain_pct = simulate_trial_regain(
            params=params,
            scale=scale,
            intercept=0.0,
            start_fm=90.0,
            stop_fm=48.0,
            treatment_days=252,
            regain_days=52 * 7,
            week36_weight_lbs=180.0,
        )
        rows.append({
            **params,
            "scale": scale,
            "intercept": intercept,
            "subject_r90": fit_r,
            "mean_gate_fit": float(np.nanmean(gate[fit_mask.values])),
            "surmount4_regain_pct": regain_pct,
            "surmount4_abs_err": abs(regain_pct - 14.0),
        })

    out = pd.DataFrame(rows)
    out["score"] = out["subject_r90"].abs() - 0.03 * out["surmount4_abs_err"]
    out = out.sort_values(["score", "subject_r90"], ascending=False).reset_index(drop=True)

    print("=" * 70)
    print("DEFENDED-DISTRIBUTION PROTOTYPE")
    print("=" * 70)
    print(f"\nTested {len(out)} parameter combinations")

    print(f"\nTop 12 by subject fit penalized by SURMOUNT-4 error:")
    cols = [
        "decay_hl_days",
        "cons_rate",
        "vel_thresh",
        "kernel_sigma",
        "pressure_band",
        "subject_r90",
        "surmount4_regain_pct",
        "surmount4_abs_err",
        "scale",
        "mean_gate_fit",
    ]
    print(out[cols].head(12).to_string(index=False, float_format=lambda x: f"{x:.3f}"))

    best = out.iloc[0]
    best_params = {k: best[k] for k in ["decay_hl_days", "cons_rate", "vel_thresh", "vel_scale", "kernel_sigma", "pressure_band"]}
    raw, gate = build_memory_pressure(fm, best_params, grid)

    df["dd_raw"] = raw
    df["dd_gate"] = gate
    df["dd_surplus_pred_90"] = best["scale"] * raw + best["intercept"]

    print(f"\nBest model summary:")
    print(f"  Subject fit (2014+ pre-tirz, surplus90): r = {best['subject_r90']:+.4f}")
    print(f"  SURMOUNT-4 predicted regain: {best['surmount4_regain_pct']:+.1f}%")
    print(f"  Pressure scale: {best['scale']:+.1f} cal per raw-unit")
    print(f"  Mean consolidation gate during fit period: {best['mean_gate_fit']:.3f}")
    print(f"  Structural params: decay HL={best['decay_hl_days']:.0f}d, cons={best['cons_rate']:.3f}, "
          f"vel_thresh={best['vel_thresh']:.3f} lb/day, sigma={best['kernel_sigma']:.1f}, band={best['pressure_band']:.1f}")

    print(f"\nYearly snapshots for best model:")
    print(f"{'Year':>6} {'FM':>6} {'Raw':>8} {'Pred90':>8} {'Gate':>7}")
    for yr in range(2014, 2027):
        sub = df[df["date"].dt.year == yr]
        if len(sub) < 60:
            continue
        print(f"{yr:>6} {sub['fat_mass_lbs_filled'].mean():>6.1f} {sub['dd_raw'].mean():>+8.3f} "
              f"{sub['dd_surplus_pred_90'].mean():>+8.1f} {sub['dd_gate'].mean():>7.3f}")

    print(f"\nInterpretation:")
    print("  This model carries a defended distribution over historically occupied FM levels.")
    print("  Pressure reflects the imbalance of defended mass above vs below current FM.")
    print("  Consolidation is continuous but velocity-gated, so rapid loss leaves old high-FM memory intact.")
    print("  If the top rows fit both the subject and SURMOUNT-4 reasonably, that is evidence that")
    print("  a continuous occupancy-memory model may subsume both EMA-like slow drift and large GLP-1 regain.")


if __name__ == "__main__":
    main()
